apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: inline-pipeline-template
spec:
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: pipelinerun-with-taskspec-to-echo-good-morning
      spec:
        pipelineSpec:
          tasks:
            - name: echo-good-morning
              taskSpec:
                metadata:
                  labels:
                    app: "example"
                steps:
                  - name: echo
                    image: icr.io/continuous-delivery/pipeline/pipeline-base-image:latest
                    script: |
                      #!/usr/bin/env bash
                      echo "ibmcloudcli version";
                      ibmcloud -version
                      echo "Good Morning!"
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: manual-inline-pipeline-binding
spec:
---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: manual-inline-listener
spec:
  triggers:
    - binding:
        name: manual-inline-pipeline-binding
      template:
        name: inline-pipeline-template
